name: test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment name to get the solution"
        required: true
        default: "DEV"
      solution_name:
        description: "Solution mane"
        required: true
        default: "PVAsolution"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-step
        uses: actions/github-script@v6
        with:
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/Sleep.js')
            
            let params = {
                solution_name: '${{ github.event.inputs.solution_name }}',
                environment: '${{ github.event.inputs.environment }}'
            }
            console.log(params)
