name: test2
on:
  workflow_dispatch:
    inputs:
      environment_url:
        description: "GitHub environment URL"
        required: true
        default: "https://orgcbe07d64.crm.dynamics.com/"
      solution_name:
        description: "Solution mane"
        required: true
        default: "PVAsolution"
      environment:
        description: "Environment name"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - run: nuget install Microsoft.PowerApps.CLI
    - run: pac.exe auth create
      shell: bash


