name: test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment name"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: exec-export-unpack-commit-solution-workflow
        id: exec-export-unpack-commit-solution-workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            let ref = '${{ github.ref }}'
            let params = {
              environment_name: '${{ github.event.inputs.environment }}',
            }
            let runId = await helper.dispatchWorkflow(github, context, 'test2.yml', ref, params)
            console.log('runId1: ' + runId)
            echo '::set-output name=runId::' + runId

      - name: check-workflow-status
        id: check-workflow-status
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let runId = ${{ steps.exec-export-unpack-commit-solution-workflow.outputs.runId }}
            console.log('runId2: ' + runId)
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            await helper.checkWorkflowStatus(github, context, core, 'test2.yml', runId, 20000)