name: test2
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Environment name"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  check-solution-existence:
    runs-on: windows-2022
    environment: ${{ github.event.inputs.environment_name }}
    steps:
      - uses: actions/checkout@v2
      - id: check-solution
        uses: ./.github/actions/check-solution-existence
        with:
          solution_name: ${{ secrets.SOLUTION_NAME }}
          environment_url: ${{ secrets.ENVIRONMENT_URL }}
          tenant_id: ${{ secrets.TENANT_ID }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          secrets: ${{ toJSON(secrets) }}
      - name: extra step
        shell: bash
        run: |
          echo "value ${{ steps.check-solution.outputs.solution_exists }}"       
    outputs:
      solution_exists: ${{ steps.check-solution.outputs.solution_exists }}
  
  delete-build-deploy-solution:
    runs-on: ubuntu-latest
    needs: check-solution-existence
    steps:
      - name: step 1
        #if: ${{ needs.check-solution-existence.outputs.solution-solution_exists }} == 'True'
        shell: bash
        run: |
          echo "step 1 ${{ needs.check-solution-existence.outputs.solution_exists }}"
      - name: step 2
        #if: ${{ needs.check-solution-existence.outputs.solution-solution_exists }} == 'False'
        shell: bash
        run: |
          echo "step 2 ${{ needs.check-solution-existence.outputs.solution_exists }}"


