name: test2
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Environment name"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  check-solution-existence:
    runs-on: windows-2022
    environment: ${{ github.event.inputs.environment_name }}
    steps:
      - uses: actions/checkout@v2
      - id: check-solution
        uses: ./.github/actions/check-solution-existence
        with:
          solution_name: ${{ secrets.SOLUTION_NAME }}
          environment_url: ${{ secrets.ENVIRONMENT_URL }}
          tenant_id: ${{ secrets.TENANT_ID }}
          app_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          secrets: ${{ toJSON(secrets) }}
    outputs:
      exists: ${{ steps.check-solution.exists }}


