name: test
on:
  workflow_dispatch:
    inputs:
      environment_url:
        description: "GitHub environment URL"
        required: true
        default: "https://orgcbe07d64.crm.dynamics.com/"
      solution_name:
        description: "Solution mane"
        required: true
        default: "PVAsolution"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-step
        uses: actions/github-script@v6
        with:
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/Sleep.js')
            
            let params = {
                solution_name: '${{ github.event.inputs.solution_name }}',
                environment_url: '${{ github.event.inputs.environment_url }}',
                source_branch: 'main',
                branch_to_create: 'test_branch_2',
                commit_message: 'commit message'
            }
            console.log(params)
            console.log(github)
            console.log(github.ref)
            console.log(context)
            await sleep.createWorkflowDispatch(github, context, params)
