name: test
on:
  workflow_dispatch:
    inputs:
      environment_url:
        description: "GitHub environment URL"
        required: true
        default: "https://orgcbe07d64.crm.dynamics.com/"
      solution_name:
        description: "Solution mane"
        required: true
        default: "PVAsolution"
      environment:
        description: "Environment name"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-step
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/Sleep.js')
            
            let params = {
                solution_name: '${{ github.event.inputs.solution_name }}',
                environment_url: '${{ github.event.inputs.environment_url }}',
                source_branch: 'main',
                branch_to_create: 'test_branch_2',
                commit_message: 'commit message'
            }

            await helper.createWorkflowDispatch(github, '${{ github.ref }}', context, params)
            await helper.checkStatus(github, context, core)
            //await helper.checkEnvironment(github, context, '${{ github.event.inputs.environment }}')
