name: trigger-determine-solution
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  trigger-determine-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: determine-solution-build-deploy-test
        id:  determine-solution-build-deploy-test
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              workflow_id: 'determine-solution-build-deploy.yml',
              ref: '${{ github.ref }}'              
            })
      
      - name: check-workflow-status
        id: check-workflow-status
        uses: actions/github-script@v5
        with:
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/test.js')
            let currentStatus = null;
            sleep(2000)
            do {
              let workflowLog = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'determine-solution-build-deploy.yml',
                per_page: 1
              })
              
              if (workflowLog.data.total_count > 0) {
                currentStatus = workflowLog.data.workflow_runs[0].status
              }
              else {
                break
              }
              console.log('determine-solution-build-deploy status: ' + currentStatus)
              sleep(20000)
            } while (currentStatus != 'completed');
          
      - name: check-build-deploy-solution-workflow-status
        id: check-build-deploy-solution-workflow-status
        uses: actions/github-script@v5
        with:
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/test.js')
            let currentStatus = null;
            sleep(2000)
            do {
              let workflowLog = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'build-deploy-solution.yml',
                per_page: 1
              })
              
              if (workflowLog.data.total_count > 0) {
                currentStatus = workflowLog.data.workflow_runs[0].status
              }
              else {
                break
              }
              console.log('build-deploy-solution: ' + currentStatus)
              sleep(20000)
            } while (currentStatus != 'completed');
